### PR TITLE
Add Plumber's Summit 2024 articles

### PR DESCRIPTION
**Pull request by ericgregory**
Submitting Plumber's Summit 2024 summary articles.

### CODE REVIEW

**Comment by disquisitioner** [comment]
Thanks, Eric!   I noticed the cross links between the two articles don't work. At the end of the day 1 article it says "Check out [our summary of Day 2](https://bytecodealliance.org/articles/plumbers-summit-day-1)" though the link for the day 2 article is https://bytecodealliance.org/articles/plumbers-day-2.

Similarly at the beginning of the day 2 recap it says "You can read a [summary of the summit’s first day](https://bytecodealliance.org/articles/plumbers-summit-day-1) on the..." but the link there should be https://bytecodealliance.org/articles/plumbers-day-1.

With those corrected I think we're good to go!

**Comment by ericgregory** [comment]
Thanks for the catches @disquisitioner! Should be all set now.

**Comment by disquisitioner** [comment]
In the course of simultaneously reviewing a blog post from @sunfishcode announcing WASI Preview 2, he and the reviewers there have decided they should replace references to "Preview 2" and "Preview 3" with "0.2" and "0.3" respectively.  They've gotten feedback that "Preview 2" confuses some people relative to references to 0.2.   I know you've used both naming schemes here, @ericgregory.  Do you want to change any of the occurrences of "Preview N" to "0.N"?  You can see how he's doing that here: https://blog.sunfishcode.online/wasi-preview2/

**Comment by sunfishcode** [comment]
I've also now renamed the blog post; the old URL is still live, but the new URL is https://blog.sunfishcode.online/wasi-0.2/

**Comment by ericgregory** [comment]
Appreciate the coordination @disquisitioner -- I've updated the remaining instances of "Preview N" to "0.N" across both posts.

**Pull request merged**
